[package]
name = "progress"
version = "0.1.0"
authors = ["pjmp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = {version = "0.15.0", default-features = false, features = ["rayon"]}
rayon = "1.5.0"
